common: &default_settings
  STRIPE_API_KEY: "sk_test_51KnWMELHxDCOABxzbLArxqOPDJT1AkfXSs5bZsQWlUyCHMv8qWyMAC4B0Do43n6JyUGahgQLbhHt0EQw0tvUnv7R00Mtv2rqbn"

test:
  <<: *default_settings

development:
  RAILS_ENV: "development"
  RACK_ENV: "development"
  <<: *default_settings
