default: &default
  adapter: postgresql
  encoding: unicode
  database: rails_production
  username: forge
  password: forge
  host:     127.0.0.1

development:
  <<: *default
  database: flatirons_saas_development

test:
  <<: *default
  database: flatirons_saas_test

production:
  <<: *default
  database: flatirons_saas_production
