---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/dummy_users/payment_methods":
    get:
      summary: List payment methods
      tags:
      - Payment Methods
      description: Lists current user payment methods.
      security:
      - bearer: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    object:
                      type: string
                    billing_details:
                      type: object
                    card:
                      type: object
                    created:
                      type: integer
                    customer:
                      type: string
                    livemode:
                      type: boolean
                    metadata:
                      type: object
                    type:
                      type: string
    post:
      summary: Attach payment method
      tags:
      - Payment Methods
      description: Lists current user payment methods.
      security:
      - bearer: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                set_as_default:
                  type: boolean
                  nullable: true
              require:
              - id
  "/dummy_users/subscriptions":
    get:
      summary: List dummy user subscriptions
      tags:
      - Subscription
      description: Lists current user subscriptions.
      security:
      - bearer: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    stripe_subscription_id:
                      type: string
                    subscriptable_type:
                      type: string
                    subscriptable_id:
                      type: integer
                    status:
                      type: string
                    deleted_at:
                      type: string
                      nullable: true
                    canceled_at:
                      type: string
                      nullable: true
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: http://localhost:3001
