---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/dummy_users/payment_methods":
    get:
      summary: List payment methods
      tags:
      - Payment Methods
      description: Lists current user payment methods.
      security:
      - bearer: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: test_pm_2
                    object: payment_method
                    type: card
                    billing_details:
                      address:
                        city: New Orleans
                        country: US
                        line1: Bourbon Street 23
                        line2: 
                        postal_code: '10000'
                        state: 
                      email: foo@bar.com
                      name: John Dolton
                      phone: 
                    customer: test_cus_1
                    metadata:
                      order_id: '123456789'
                    card:
                      brand: visa
                      checks:
                        address_line1_check: 
                        address_postal_code_check: 
                        cvc_check: pass
                      country: FR
                      exp_month: 10
                      exp_year: 2050
                      fingerprint: Hr3Ly5z5IYxsokWA
                      funding: credit
                      generated_from: 
                      last4: '4242'
                      three_d_secure_usage:
                        supported: true
                      wallet: 
                  - id: test_pm_3
                    object: payment_method
                    type: card
                    billing_details:
                      address:
                        city: New Orleans
                        country: US
                        line1: Bourbon Street 23
                        line2: 
                        postal_code: '10000'
                        state: 
                      email: foo@bar.com
                      name: John Dolton
                      phone: 
                    customer: test_cus_1
                    metadata:
                      order_id: '123456789'
                    card:
                      brand: visa
                      checks:
                        address_line1_check: 
                        address_postal_code_check: 
                        cvc_check: pass
                      country: FR
                      exp_month: 10
                      exp_year: 2050
                      fingerprint: Hr3Ly5z5IYxsokWA
                      funding: credit
                      generated_from: 
                      last4: '4242'
                      three_d_secure_usage:
                        supported: true
                      wallet: 
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    object:
                      type: string
                    billing_details:
                      type: object
                    card:
                      type: object
                    created:
                      type: integer
                    customer:
                      type: string
                    livemode:
                      type: boolean
                    metadata:
                      type: object
                    type:
                      type: string
    post:
      summary: Attach payment method
      tags:
      - Payment Methods
      description: Lists current user payment methods.
      security:
      - bearer: []
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: test_pm_4
                    object: payment_method
                    type: card
                    billing_details:
                      address:
                        city: New Orleans
                        country: US
                        line1: Bourbon Street 23
                        line2: 
                        postal_code: '10000'
                        state: 
                      email: foo@bar.com
                      name: John Dolton
                      phone: 
                    customer: test_cus_1
                    metadata:
                      order_id: '123456789'
                    card:
                      brand: visa
                      checks:
                        address_line1_check: 
                        address_postal_code_check: 
                        cvc_check: pass
                      country: FR
                      exp_month: 10
                      exp_year: 2050
                      fingerprint: Hr3Ly5z5IYxsokWA
                      funding: credit
                      generated_from: 
                      last4: '4242'
                      three_d_secure_usage:
                        supported: true
                      wallet: 
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                set_as_default:
                  type: boolean
                  nullable: true
              require:
              - id
  "/dummy_users/products":
    get:
      summary: List products
      tags:
      - Product
      description: Lists products.
      security:
      - bearer: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 89
                    name: Scot Kuhic
                    stripe_product_id: test_prod_2
                    description: 
                    deleted_at: 
                    created_at: '2022-07-14T18:07:49.707Z'
                    updated_at: '2022-07-14T18:07:49.707Z'
                  - id: 90
                    name: Aubrey Yundt
                    stripe_product_id: test_prod_3
                    description: 
                    deleted_at: 
                    created_at: '2022-07-14T18:07:49.719Z'
                    updated_at: '2022-07-14T18:07:49.719Z'
                  - id: 91
                    name: Hans Emmerich
                    stripe_product_id: test_prod_4
                    description: 
                    deleted_at: 
                    created_at: '2022-07-14T18:07:49.729Z'
                    updated_at: '2022-07-14T18:07:49.729Z'
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    stripe_product_id:
                      type: string
                    name:
                      type: string
                    description:
                      type: string
                      nullable: true
                    deleted_at:
                      type: string
                      nullable: true
                    created_at:
                      type: string
                    updated_at:
                      type: string
  "/dummy_users/subscriptions":
    get:
      summary: List dummy user subscriptions
      tags:
      - Subscription
      description: Lists current user subscriptions.
      security:
      - bearer: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 83
                    stripe_subscription_id: 2f8dd226-512e-486f-b868-94efc300d8fe
                    status: active
                    subscriptable_type: DummyUser
                    subscriptable_id: 94
                    deleted_at: 
                    canceled_at: 
                    created_at: '2022-07-14T18:07:49.779Z'
                    updated_at: '2022-07-14T18:07:49.779Z'
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    stripe_subscription_id:
                      type: string
                    subscriptable_type:
                      type: string
                    subscriptable_id:
                      type: integer
                    status:
                      type: string
                    deleted_at:
                      type: string
                      nullable: true
                    canceled_at:
                      type: string
                      nullable: true
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: http://localhost:3001
