name: Release
on:
  workflow_call:
jobs:
  build:
    steps:
      - name: Release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/scripts/deploy-gem.sh"
          "${GITHUB_WORKSPACE}/.github/scripts/deploy-gem.sh" "${GITHUB_TOKEN}" "flatironsdevelopment"
